29/06/2020 12:09:01 PM Python Script is: morePVs.py
29/06/2020 12:09:01 PM study_name = demo_wenapt
29/06/2020 12:09:02 PM Running Scenario number 0 
29/06/2020 12:09:05 PM 


 Exception !!!!!!
Traceback (most recent call last):
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 2640, in main
    runScenario(s)
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 2580, in runScenario
    eno.calcBuildingStaticEnergyFlows()
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 1445, in calcBuildingStaticEnergyFlows
    self.cum_local_imports += self.resident[c].solar_allocation
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 1445, in calcBuildingStaticEnergyFlows
    self.cum_local_imports += self.resident[c].solar_allocation
  File "_pydevd_bundle/pydevd_cython_darwin_37_64.pyx", line 1563, in _pydevd_bundle.pydevd_cython_darwin_37_64.ThreadTracer.__call__
  File "_pydevd_bundle/pydevd_cython_darwin_37_64.pyx", line 903, in _pydevd_bundle.pydevd_cython_darwin_37_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython_darwin_37_64.pyx", line 894, in _pydevd_bundle.pydevd_cython_darwin_37_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython_darwin_37_64.pyx", line 317, in _pydevd_bundle.pydevd_cython_darwin_37_64.PyDBFrame.do_wait_suspend
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1103, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1118, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
