30/08/2019 10:51:54 AM Python Script is: morePVs.py
30/08/2019 10:51:54 AM study_name = test_capex1
30/08/2019 10:51:55 AM Running Scenario number 1 
30/08/2019 10:51:57 AM Completed Scenario 1
30/08/2019 10:51:57 AM Running Scenario number 2 
30/08/2019 10:51:59 AM 


 Exception !!!!!!
Traceback (most recent call last):
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 2653, in main
    runScenario(s)
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 2616, in runScenario
    eno.allocateAllCapex(scenario)  # per load profile to allow for scenarios where capex allocation depends on load
  File "/Users/mikeroberts/Documents/python/morePVs/morePVs.py", line 1603, in allocateAllCapex
    self.resident[c].pv_capex_repayment = self.pv[c].sum() / self.pv.sum().sum() * scenario.pv_capex_repayment['total_system']
KeyError: 'total_system'
